"""event dedup key

Revision ID: c4178e646d51
Revises: 9e5670b529d7
Create Date: 2026-05-25 15:44:43.864851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4178e646d51'
down_revision = '9e5670b529d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_log', sa.Column('dedup_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_log', 'dedup_key')
    # ### end Alembic commands ###
