"""cards data json

Revision ID: 3b8e47f4dd52
Revises: 62f0a10a42d8
Create Date: 2026-03-25 15:01:16.183929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b8e47f4dd52'
down_revision = '62f0a10a42d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('newly_added', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('cards', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('enemies', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('enemy_leaders', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('leaders', sa.Column('newly_added', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('leaders', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaders', 'data')
    op.drop_column('leaders', 'newly_added')
    op.drop_column('enemy_leaders', 'data')
    op.drop_column('enemies', 'data')
    op.drop_column('cards', 'data')
    op.drop_column('cards', 'newly_added')
    # ### end Alembic commands ###
