"""fix len of fields

Revision ID: afd337f652f2
Revises: 8ce99d743fcd
Create Date: 2026-01-06 21:02:21.148462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd337f652f2'
down_revision = '8ce99d743fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('abilities', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('cards', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('colors', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('deathwishes', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('enemies', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('enemy_leader_abilities', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('enemy_leaders', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('enemy_passive_abilities', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('factions', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('leaders', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('moves', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('passive_abilities', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('types', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('types', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('passive_abilities', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('moves', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('leaders', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('factions', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('enemy_passive_abilities', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('enemy_leaders', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('enemy_leader_abilities', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('enemies', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('deathwishes', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('colors', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('cards', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('abilities', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
