"""user_level

Revision ID: 8aaf7089b53b
Revises: d28aa194940d
Create Date: 2026-01-10 08:27:49.344045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aaf7089b53b'
down_revision = 'd28aa194940d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_levels')
    # ### end Alembic commands ###
