"""leader hp

Revision ID: bf3b1717d01c
Revises: 4e190f6c615f
Create Date: 2026-02-10 14:14:23.427188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3b1717d01c'
down_revision = '4e190f6c615f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaders', sa.Column('hp', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaders', 'hp')
    # ### end Alembic commands ###
