"""counts in user_cards, user_decks

Revision ID: d28aa194940d
Revises: a540ee70523e
Create Date: 2026-01-09 09:06:36.325425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28aa194940d'
down_revision = 'a540ee70523e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_cards', sa.Column('count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_leaders', sa.Column('count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_leaders', 'count')
    op.drop_column('user_cards', 'count')
    # ### end Alembic commands ###
