"""user_resources new

Revision ID: d8fcef0396d1
Revises: b33216bf9df7
Create Date: 2026-02-25 22:38:42.159791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fcef0396d1'
down_revision = 'b33216bf9df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_resources', sa.Column('raw_bronze', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_resources', sa.Column('raw_silver', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_resources', sa.Column('raw_gold', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_resources', sa.Column('bronze_ingots', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_resources', sa.Column('silver_ingots', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_resources', sa.Column('gold_ingots', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_resources', sa.Column('crops', sa.Integer(), server_default='1000', nullable=False))
    op.add_column('user_resources', sa.Column('silk', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_resources', sa.Column('rare_gem', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_resources', sa.Column('money', sa.Integer(), server_default='2000', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_resources', 'money')
    op.drop_column('user_resources', 'rare_gem')
    op.drop_column('user_resources', 'silk')
    op.drop_column('user_resources', 'crops')
    op.drop_column('user_resources', 'gold_ingots')
    op.drop_column('user_resources', 'silver_ingots')
    op.drop_column('user_resources', 'bronze_ingots')
    op.drop_column('user_resources', 'raw_gold')
    op.drop_column('user_resources', 'raw_silver')
    op.drop_column('user_resources', 'raw_bronze')
    # ### end Alembic commands ###
