"""x and y of seasons tree

Revision ID: 4e190f6c615f
Revises: f85c6d375a74
Create Date: 2026-02-01 10:46:40.345306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e190f6c615f'
down_revision = 'f85c6d375a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('x', sa.Integer(), server_default='0', nullable=False))
    op.add_column('seasons', sa.Column('y', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'y')
    op.drop_column('seasons', 'x')
    # ### end Alembic commands ###
