"""change default resources

Revision ID: 4911178f99e8
Revises: 16333318798d
Create Date: 2026-05-15 16:25:58.446479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4911178f99e8'
down_revision = '16333318798d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_resources', 'kegs',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('user_resources', 'big_kegs',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('user_resources', 'keys',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('user_resources', 'money',
               existing_type=sa.INTEGER(),
               server_default='3000',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_resources', 'money',
               existing_type=sa.INTEGER(),
               server_default=sa.text('2000'),
               existing_nullable=False)
    op.alter_column('user_resources', 'keys',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('user_resources', 'big_kegs',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('user_resources', 'kegs',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    # ### end Alembic commands ###
