"""season_related_seasons

Revision ID: f85c6d375a74
Revises: 300ca59cc776
Create Date: 2026-02-01 09:56:56.275291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85c6d375a74'
down_revision = '300ca59cc776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season_related_seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('related_season_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.String(length=16), nullable=True),
    sa.Column('connection', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'related_season_id', name='uq_season_related_seasons')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('season_related_seasons')
    # ### end Alembic commands ###
