"""new resources

Revision ID: 5265d8e531d8
Revises: 1adf965f6359
Create Date: 2026-06-03 12:28:17.624532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5265d8e531d8'
down_revision = '1adf965f6359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_resources', sa.Column('flowers', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_resources', sa.Column('first_aid_kits', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_resources', sa.Column('shields', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_resources', 'shields')
    op.drop_column('user_resources', 'first_aid_kits')
    op.drop_column('user_resources', 'flowers')
    # ### end Alembic commands ###
