"""resized images

Revision ID: b52baa46a8c2
Revises: afd337f652f2
Create Date: 2026-01-07 12:04:28.467722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52baa46a8c2'
down_revision = 'afd337f652f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('image_original', sa.String(length=255), nullable=False))
    op.add_column('cards', sa.Column('image_tablet', sa.String(length=255), nullable=False))
    op.add_column('cards', sa.Column('image_phone', sa.String(length=255), nullable=False))
    op.drop_column('cards', 'image')
    op.add_column('enemies', sa.Column('image_original', sa.String(length=255), nullable=False))
    op.add_column('enemies', sa.Column('image_tablet', sa.String(length=255), nullable=False))
    op.add_column('enemies', sa.Column('image_phone', sa.String(length=255), nullable=False))
    op.drop_column('enemies', 'image')
    op.add_column('enemy_leaders', sa.Column('image_original', sa.String(length=255), nullable=False))
    op.add_column('enemy_leaders', sa.Column('image_tablet', sa.String(length=255), nullable=False))
    op.add_column('enemy_leaders', sa.Column('image_phone', sa.String(length=255), nullable=False))
    op.drop_column('enemy_leaders', 'image')
    op.add_column('leaders', sa.Column('image_original', sa.String(length=255), nullable=False))
    op.add_column('leaders', sa.Column('image_tablet', sa.String(length=255), nullable=False))
    op.add_column('leaders', sa.Column('image_phone', sa.String(length=255), nullable=False))
    op.drop_column('leaders', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaders', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('leaders', 'image_phone')
    op.drop_column('leaders', 'image_tablet')
    op.drop_column('leaders', 'image_original')
    op.add_column('enemy_leaders', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('enemy_leaders', 'image_phone')
    op.drop_column('enemy_leaders', 'image_tablet')
    op.drop_column('enemy_leaders', 'image_original')
    op.add_column('enemies', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('enemies', 'image_phone')
    op.drop_column('enemies', 'image_tablet')
    op.drop_column('enemies', 'image_original')
    op.add_column('cards', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('cards', 'image_phone')
    op.drop_column('cards', 'image_tablet')
    op.drop_column('cards', 'image_original')
    # ### end Alembic commands ###
