"""leaders migration

Revision ID: 6af676f87b92
Revises: 1c7d2c107e5c
Create Date: 2026-01-05 22:17:42.235614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af676f87b92'
down_revision = '1c7d2c107e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('unlocked', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('charges', sa.Integer(), server_default='1', nullable=False),
    sa.Column('heal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('has_passive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('passive_ability_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('timer', sa.Integer(), server_default='0', nullable=False),
    sa.Column('default_timer', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reset_timer', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passive_ability_id'], ['passive_abilities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_leader_name')
    )
    op.create_unique_constraint('uq_ability_name', 'abilities', ['name'])
    op.create_unique_constraint('uq_color_name', 'colors', ['name'])
    op.create_unique_constraint('uq_faction_name', 'factions', ['name'])
    op.create_unique_constraint('uq_passive_ability_name', 'passive_abilities', ['name'])
    op.create_unique_constraint('uq_type_name', 'types', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_type_name', 'types', type_='unique')
    op.drop_constraint('uq_passive_ability_name', 'passive_abilities', type_='unique')
    op.drop_constraint('uq_faction_name', 'factions', type_='unique')
    op.drop_constraint('uq_color_name', 'colors', type_='unique')
    op.drop_constraint('uq_ability_name', 'abilities', type_='unique')
    op.drop_table('leaders')
    # ### end Alembic commands ###
