"""timestamp in cards

Revision ID: 6941bca133b2
Revises: 3fe876f8e763
Create Date: 2026-01-15 10:19:08.409437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6941bca133b2'
down_revision = '3fe876f8e763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_decks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('card_decks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('cards', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('cards', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('decks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('decks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('enemies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('enemies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('enemy_leaders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('enemy_leaders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('leaders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('leaders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('level_enemies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('level_enemies', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('level_related_levels', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('level_related_levels', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('levels', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('levels', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('seasons', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('seasons', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_cards', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_cards', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_decks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_decks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_leaders', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_leaders', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_levels', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_levels', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_resources', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_resources', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_resources', 'updated_at')
    op.drop_column('user_resources', 'created_at')
    op.drop_column('user_levels', 'updated_at')
    op.drop_column('user_levels', 'created_at')
    op.drop_column('user_leaders', 'updated_at')
    op.drop_column('user_leaders', 'created_at')
    op.drop_column('user_decks', 'updated_at')
    op.drop_column('user_decks', 'created_at')
    op.drop_column('user_cards', 'updated_at')
    op.drop_column('user_cards', 'created_at')
    op.drop_column('seasons', 'updated_at')
    op.drop_column('seasons', 'created_at')
    op.drop_column('levels', 'updated_at')
    op.drop_column('levels', 'created_at')
    op.drop_column('level_related_levels', 'updated_at')
    op.drop_column('level_related_levels', 'created_at')
    op.drop_column('level_enemies', 'updated_at')
    op.drop_column('level_enemies', 'created_at')
    op.drop_column('leaders', 'updated_at')
    op.drop_column('leaders', 'created_at')
    op.drop_column('enemy_leaders', 'updated_at')
    op.drop_column('enemy_leaders', 'created_at')
    op.drop_column('enemies', 'updated_at')
    op.drop_column('enemies', 'created_at')
    op.drop_column('decks', 'updated_at')
    op.drop_column('decks', 'created_at')
    op.drop_column('cards', 'updated_at')
    op.drop_column('cards', 'created_at')
    op.drop_column('card_decks', 'updated_at')
    op.drop_column('card_decks', 'created_at')
    # ### end Alembic commands ###
