"""retry count in events

Revision ID: 9e5670b529d7
Revises: 4911178f99e8
Create Date: 2026-05-20 13:41:55.996640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e5670b529d7'
down_revision = '4911178f99e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_log', sa.Column('actions_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('event_log', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_log', 'retry_count')
    op.drop_column('event_log', 'actions_log')
    # ### end Alembic commands ###
