"""armor to card and leader

Revision ID: 62f0a10a42d8
Revises: ec4086e433ec
Create Date: 2026-03-23 14:37:19.552738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f0a10a42d8'
down_revision = 'ec4086e433ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('armor', sa.Integer(), server_default='0', nullable=False))
    op.add_column('leaders', sa.Column('armor', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaders', 'armor')
    op.drop_column('cards', 'armor')
    # ### end Alembic commands ###
