"""immune magics

Revision ID: 97e25d29d639
Revises: 5265d8e531d8
Create Date: 2026-06-17 12:11:15.843566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e25d29d639'
down_revision = '5265d8e531d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_resources', sa.Column('immune_magics', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_resources', 'immune_magics')
    # ### end Alembic commands ###
