"""cards migration

Revision ID: 1fc816467ca0
Revises: 6af676f87b92
Create Date: 2026-01-06 17:00:01.599491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc816467ca0'
down_revision = '6af676f87b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('unlocked', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), server_default='0', nullable=False),
    sa.Column('charges', sa.Integer(), server_default='1', nullable=False),
    sa.Column('hp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('heal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('has_passive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_passive_in_hand', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_passive_in_deck', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_passive_in_grave', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('passive_ability_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), server_default='0', nullable=False),
    sa.Column('timer', sa.Integer(), server_default='0', nullable=False),
    sa.Column('default_timer', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reset_timer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('each_tick', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['passive_ability_id'], ['passive_abilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
