"""unique field dedup_key

Revision ID: 1adf965f6359
Revises: c4178e646d51
Create Date: 2026-05-27 11:52:29.397866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adf965f6359'
down_revision = 'c4178e646d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event_log', ['dedup_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_log', type_='unique')
    # ### end Alembic commands ###
