"""seasons and levels

Revision ID: 639d00880e89
Revises: 5ea737423f38
Create Date: 2026-01-08 13:52:23.443493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639d00880e89'
down_revision = '5ea737423f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('starting_enemies_number', sa.Integer(), server_default='3', nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('unlocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('x', sa.Integer(), server_default='0', nullable=False),
    sa.Column('y', sa.Integer(), server_default='0', nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('enemy_leader_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enemy_leader_id'], ['enemy_leaders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('level_enemies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('enemy_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enemy_id'], ['enemies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level_related_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('related_level_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.String(length=16), nullable=True),
    sa.Column('connection', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_level_id'], ['levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'related_level_id', name='uq_level_related_levels')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('level_related_levels')
    op.drop_table('level_enemies')
    op.drop_table('levels')
    op.drop_table('seasons')
    # ### end Alembic commands ###
