from enum import StrEnum


class WSEvent(StrEnum):
    AUTH_ERROR = "AUTH_ERROR"
    WAITING_FOR_OPPONENT = "WAITING_FOR_OPPONENT"
    GAME_STARTED = "GAME_STARTED"
    OPPONENT_DISCONNECTED = "OPPONENT_DISCONNECTED"
